"""Command-line entry point: ``meshdash``.

Examples::

    meshdash live --port /dev/ttyUSB0            # real gateway
    meshdash live --replay out/sim.jsonl --speed 30
    meshdash report out/sim.jsonl --truth out/truth.json --figures docs/img --markdown out/results.md
    meshdash stack --node-log out/qemu_node.log --gateway-log out/qemu_gw.log
"""

from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Sequence
from pathlib import Path

from meshtools import __version__, plots
from meshtools.dashboard import follow_file, replay_lines, run, serial_lines
from meshtools.metrics import compute
from meshtools.records import ParseStats, read_log
from meshtools.report import (
    checks_table,
    cross_checks,
    load_truth,
    node_table,
    parse_gateway_stacks,
    parse_node_stacks,
    stack_table,
    summary_table,
    truth_table,
)

_GW_TASK = re.compile(r'\[T_\w+\]\s*=\s*\{"(\w+)",\s*(\d+),')


def _cmd_live(args: argparse.Namespace) -> int:
    if args.port:
        lines = serial_lines(args.port, args.baud)
    elif args.replay:
        fh = Path(args.replay).open(encoding="utf-8", errors="replace")  # noqa: SIM115 - closed at exit
        lines = replay_lines(fh, args.speed)
    elif args.follow:
        lines = follow_file(Path(args.follow))
    else:
        lines = iter(sys.stdin)
    run(lines, max_lines=args.max_lines)
    return 0


def _cmd_report(args: argparse.Namespace) -> int:
    stats = ParseStats()
    records = read_log(args.log, stats)
    mm, act = compute(records, bin_s=args.bin)
    truth = load_truth(args.truth) if args.truth else None
    checks = cross_checks(mm, truth)
    parts = [
        f"<!-- generated by meshdash {__version__} from {Path(args.log).name}: "
        f"{stats.records} records, {stats.non_json} non-JSON lines, {stats.malformed} malformed -->",
        "### Mesh-wide",
        summary_table(mm),
        "",
        "### Per node",
        node_table(mm),
        "",
        "### Consistency checks",
        checks_table(checks),
    ]
    if truth is not None:
        parts += ["", "### Simulator ground truth (node side)", truth_table(truth)]
    text = "\n".join(parts) + "\n"
    if args.markdown:
        Path(args.markdown).parent.mkdir(parents=True, exist_ok=True)
        Path(args.markdown).write_text(text, encoding="utf-8")
    print(text)
    if args.figures:
        out = Path(args.figures)
        plots.activity_heatmap(act, out / "activity_heatmap.png")
        plots.state_timeline(mm, out / "node_states.png")
        plots.loss_and_retries(mm, out / "loss_retries.png")
        plots.latency_cdfs(mm, out / "latency_cdf.png")
        if args.gif:
            plots.replay_gif(mm, act, out / "dashboard_replay.gif")
    failed = [c for c in checks if not c.ok]
    for c in failed:
        print(f"consistency check FAILED: {c.name}: expected {c.expected}, got {c.actual}", file=sys.stderr)
    return 1 if failed and args.strict else 0


def _cmd_stack(args: argparse.Namespace) -> int:
    rows = []
    if args.node_log:
        rows += parse_node_stacks(Path(args.node_log).read_text(encoding="utf-8", errors="replace"))
    if args.gateway_log:
        sizes = {m.group(1): int(m.group(2)) for m in _GW_TASK.finditer(Path(args.gateway_src).read_text())}
        text = Path(args.gateway_log).read_text(encoding="utf-8", errors="replace")
        rows += parse_gateway_stacks(text, sizes)
    table = stack_table(rows)
    if args.markdown:
        Path(args.markdown).write_text(table + "\n", encoding="utf-8")
    print(table)
    return 0 if rows else 1


def build_parser() -> argparse.ArgumentParser:
    """Build the argument parser (exposed for tests)."""
    p = argparse.ArgumentParser(prog="meshdash", description=__doc__.splitlines()[0] if __doc__ else None)
    p.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    sub = p.add_subparsers(dest="cmd", required=True)

    live = sub.add_parser("live", help="live terminal dashboard")
    src = live.add_mutually_exclusive_group()
    src.add_argument("--port", help="gateway serial port, e.g. /dev/ttyUSB0 or COM5")
    src.add_argument("--replay", help="replay a finished log")
    src.add_argument("--follow", help="follow a growing log file")
    live.add_argument("--baud", type=int, default=921600)
    live.add_argument("--speed", type=float, default=20.0, help="replay speed-up factor (0 = no delay)")
    live.add_argument("--max-lines", type=int, default=None)
    live.set_defaults(func=_cmd_live)

    rep = sub.add_parser("report", help="metrics tables, consistency checks and figures")
    rep.add_argument("log")
    rep.add_argument("--truth", help="simulator ground-truth JSON")
    rep.add_argument("--figures", help="directory for PNG figures")
    rep.add_argument("--gif", action="store_true", help="also render the animated replay GIF")
    rep.add_argument("--markdown", help="write the tables to this file")
    rep.add_argument("--bin", type=float, default=10.0, help="activity bin width (s)")
    rep.add_argument("--strict", action="store_true", help="exit 1 if a consistency check fails")
    rep.set_defaults(func=_cmd_report)

    stk = sub.add_parser("stack", help="stack high-water-mark table from QEMU/hardware logs")
    stk.add_argument("--node-log")
    stk.add_argument("--gateway-log")
    stk.add_argument("--gateway-src", default="gateway/main/gw_tasks.c")
    stk.add_argument("--markdown")
    stk.set_defaults(func=_cmd_stack)
    return p


def main(argv: Sequence[str] | None = None) -> int:
    """Entry point."""
    args = build_parser().parse_args(argv)
    rc: int = args.func(args)
    return rc


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
