"""Python mirror of the mesh wire protocol (``components/mesh_protocol``).

The firmware is the reference implementation; this module exists so that host
tools can decode raw frames (e.g. captured with a sniffer) and so that the
test-suite can check the C codec against an independent implementation using
golden vectors generated by ``host/tools/mesh_vectors.c``.

All multi-byte fields are little-endian. See ``docs/PROTOCOL.md``.
"""

from __future__ import annotations

import struct
from dataclasses import dataclass, field
from enum import IntEnum

MAGIC = 0x4D
VERSION = 1
FRAME_MAX = 250
HEADER_SIZE = 14
TRAILER_SIZE = 2
MAX_CHANNELS = 20
HB_MAX_TASKS = 6

FLAG_ACK_REQ = 0x01
FLAG_ENCRYPTED = 0x02

_HEADER = struct.Struct("<BBBBHHIBB")
_JOIN = struct.Struct("<IIIIBB")
_JOIN_ACK = struct.Struct("<BBI")
_DATA_FIXED = struct.Struct("<BBIB")
_CHANNEL = struct.Struct("<Bi")
_HEARTBEAT = struct.Struct("<IIIIIIIIIbB" + "H" * HB_MAX_TASKS)
_ACK = struct.Struct("<HBBBb")
_CONFIG = struct.Struct("<BI")


class MsgType(IntEnum):
    """Message types (``mesh_msg_type_t``)."""

    JOIN = 1
    JOIN_ACK = 2
    DATA = 3
    HEARTBEAT = 4
    ACK = 5
    CONFIG = 6


class ProtocolError(ValueError):
    """Raised when a frame fails validation; ``code`` matches ``mesh_err_str``."""

    def __init__(self, code: str, message: str) -> None:
        """Create an error with a stable machine-readable ``code``."""
        super().__init__(f"{code}: {message}")
        self.code = code


def crc16_ccitt(data: bytes, crc: int = 0xFFFF) -> int:
    """CRC-16/CCITT-FALSE (poly 0x1021, init 0xFFFF, no reflection, no xor-out).

    Args:
        data: Bytes to checksum.
        crc: Initial value, allowing incremental computation.

    Returns:
        The 16-bit CRC.
    """
    for byte in data:
        crc ^= byte << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xFFFF if crc & 0x8000 else (crc << 1) & 0xFFFF
    return crc


@dataclass(frozen=True)
class Header:
    """Decoded frame header."""

    type: int
    flags: int
    node_id: int
    seq: int
    uptime_ms: int
    attempt: int = 1


@dataclass(frozen=True)
class JoinPayload:
    """JOIN payload: announcement of a (re)booted node."""

    fw_version: int
    boot_count: int
    report_interval_ms: int
    heartbeat_interval_ms: int
    backend: int
    reset_reason: int


@dataclass(frozen=True)
class JoinAckPayload:
    """JOIN_ACK payload."""

    status: int
    wifi_channel: int
    offline_timeout_ms: int


@dataclass(frozen=True)
class DataPayload:
    """DATA payload: one reading made of (quantity, value x 1000) channels."""

    backend: int
    status: int
    last_rtt_us: int
    channels: tuple[tuple[int, int], ...] = ()


@dataclass(frozen=True)
class HeartbeatPayload:
    """HEARTBEAT payload: node health telemetry."""

    uptime_s: int
    free_heap: int
    min_free_heap: int
    tx_ok: int
    tx_retries: int
    tx_failed: int
    queue_drops: int
    rtt_avg_us: int
    rtt_max_us: int
    last_ack_rssi: int
    task_count: int
    stack_hwm: tuple[int, ...] = field(default=(0,) * HB_MAX_TASKS)


@dataclass(frozen=True)
class AckPayload:
    """ACK payload."""

    acked_seq: int
    acked_type: int
    acked_attempt: int
    status: int
    rssi: int


@dataclass(frozen=True)
class ConfigPayload:
    """CONFIG payload."""

    key: int
    value: int


Payload = JoinPayload | JoinAckPayload | DataPayload | HeartbeatPayload | AckPayload | ConfigPayload


@dataclass(frozen=True)
class Frame:
    """A complete decoded frame."""

    header: Header
    payload: Payload


def _encode_payload(ftype: int, p: Payload) -> bytes:
    if ftype == MsgType.JOIN and isinstance(p, JoinPayload):
        return _JOIN.pack(
            p.fw_version,
            p.boot_count,
            p.report_interval_ms,
            p.heartbeat_interval_ms,
            p.backend,
            p.reset_reason,
        )
    if ftype == MsgType.JOIN_ACK and isinstance(p, JoinAckPayload):
        return _JOIN_ACK.pack(p.status, p.wifi_channel, p.offline_timeout_ms)
    if ftype == MsgType.DATA and isinstance(p, DataPayload):
        if len(p.channels) > MAX_CHANNELS:
            raise ProtocolError("bad_payload", "too many channels")
        body = _DATA_FIXED.pack(p.backend, p.status, p.last_rtt_us, len(p.channels))
        return body + b"".join(_CHANNEL.pack(q, v) for q, v in p.channels)
    if ftype == MsgType.HEARTBEAT and isinstance(p, HeartbeatPayload):
        hwm = tuple(p.stack_hwm) + (0,) * (HB_MAX_TASKS - len(p.stack_hwm))
        return _HEARTBEAT.pack(
            p.uptime_s,
            p.free_heap,
            p.min_free_heap,
            p.tx_ok,
            p.tx_retries,
            p.tx_failed,
            p.queue_drops,
            p.rtt_avg_us,
            p.rtt_max_us,
            p.last_ack_rssi,
            p.task_count,
            *hwm[:HB_MAX_TASKS],
        )
    if ftype == MsgType.ACK and isinstance(p, AckPayload):
        return _ACK.pack(p.acked_seq, p.acked_type, p.acked_attempt, p.status, p.rssi)
    if ftype == MsgType.CONFIG and isinstance(p, ConfigPayload):
        return _CONFIG.pack(p.key, p.value)
    raise ProtocolError("bad_type", f"payload {type(p).__name__} does not match type {ftype}")


def encode(frame: Frame) -> bytes:
    """Serialise a frame exactly like ``mesh_encode`` (header, payload, CRC).

    Args:
        frame: Frame to encode.

    Returns:
        The wire bytes.

    Raises:
        ProtocolError: If the payload does not match the type or is too large.
    """
    h = frame.header
    payload = _encode_payload(h.type, frame.payload)
    if HEADER_SIZE + len(payload) + TRAILER_SIZE > FRAME_MAX:
        raise ProtocolError("no_space", "frame exceeds 250 bytes")
    body = (
        _HEADER.pack(MAGIC, VERSION, h.type, h.flags, h.node_id, h.seq, h.uptime_ms, h.attempt, len(payload))
        + payload
    )
    return body + struct.pack("<H", crc16_ccitt(body))


def _decode_payload(ftype: int, raw: bytes) -> Payload:
    fixed: dict[int, struct.Struct] = {
        MsgType.JOIN: _JOIN,
        MsgType.JOIN_ACK: _JOIN_ACK,
        MsgType.HEARTBEAT: _HEARTBEAT,
        MsgType.ACK: _ACK,
        MsgType.CONFIG: _CONFIG,
    }
    if ftype == MsgType.DATA:
        if len(raw) < _DATA_FIXED.size:
            raise ProtocolError("bad_payload", "data payload too short")
        backend, status, rtt, count = _DATA_FIXED.unpack_from(raw)
        if count > MAX_CHANNELS or len(raw) != _DATA_FIXED.size + count * _CHANNEL.size:
            raise ProtocolError("bad_payload", "channel count does not match payload length")
        chans = tuple(_CHANNEL.unpack_from(raw, _DATA_FIXED.size + i * _CHANNEL.size) for i in range(count))
        return DataPayload(backend, status, rtt, tuple((int(q), int(v)) for q, v in chans))
    st = fixed.get(ftype)
    if st is None:
        raise ProtocolError("bad_type", f"unknown message type {ftype}")
    if len(raw) != st.size:
        raise ProtocolError("bad_payload", f"expected {st.size} bytes, got {len(raw)}")
    v = st.unpack(raw)
    if ftype == MsgType.JOIN:
        return JoinPayload(*v)
    if ftype == MsgType.JOIN_ACK:
        return JoinAckPayload(*v)
    if ftype == MsgType.HEARTBEAT:
        if v[10] > HB_MAX_TASKS:
            raise ProtocolError("bad_payload", "task_count out of range")
        return HeartbeatPayload(
            uptime_s=v[0],
            free_heap=v[1],
            min_free_heap=v[2],
            tx_ok=v[3],
            tx_retries=v[4],
            tx_failed=v[5],
            queue_drops=v[6],
            rtt_avg_us=v[7],
            rtt_max_us=v[8],
            last_ack_rssi=v[9],
            task_count=v[10],
            stack_hwm=tuple(v[11:]),
        )
    if ftype == MsgType.ACK:
        return AckPayload(*v)
    return ConfigPayload(*v)


def decode(buf: bytes) -> Frame:
    """Validate and decode a frame, applying the same checks in the same order as ``mesh_decode``.

    Args:
        buf: Raw frame bytes.

    Returns:
        The decoded frame.

    Raises:
        ProtocolError: With ``code`` equal to the firmware's ``mesh_err_str`` value.
    """
    if len(buf) < HEADER_SIZE + TRAILER_SIZE:
        raise ProtocolError("too_short", f"{len(buf)} bytes")
    if buf[0] != MAGIC:
        raise ProtocolError("bad_magic", f"0x{buf[0]:02x}")
    if buf[1] != VERSION:
        raise ProtocolError("bad_version", str(buf[1]))
    plen = buf[13]
    if len(buf) > FRAME_MAX or len(buf) != HEADER_SIZE + plen + TRAILER_SIZE:
        raise ProtocolError("bad_length", f"declared {plen}, got {len(buf) - HEADER_SIZE - TRAILER_SIZE}")
    body = buf[: HEADER_SIZE + plen]
    (rx_crc,) = struct.unpack_from("<H", buf, HEADER_SIZE + plen)
    if crc16_ccitt(body) != rx_crc:
        raise ProtocolError("bad_crc", f"0x{rx_crc:04x}")
    _, _, ftype, flags, node_id, seq, uptime, attempt, _ = _HEADER.unpack_from(buf)
    header = Header(ftype, flags, node_id, seq, uptime, attempt)
    return Frame(header, _decode_payload(ftype, bytes(buf[HEADER_SIZE : HEADER_SIZE + plen])))


def seq_diff(a: int, b: int) -> int:
    """Signed 16-bit serial-number distance ``a - b`` (RFC 1982)."""
    d = (a - b) & 0xFFFF
    return d - 0x10000 if d & 0x8000 else d
